spring:
  datasource:
    url: jdbc:h2:file:./data/database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console  # URL padrão do console
      settings:
        web-allow-others: false  # Segurança: não permitir acesso remoto

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true  # Certifique-se de que o Flyway está configurado para H2